export const pokemonData = new Map<string, string>([
  ["bulbasaur", "フシギダネ"], // 1
  ["ivysaur", "フシギソウ"], // 2
  ["venusaur", "フシギバナ"], // 3
  ["charmander", "ヒトカゲ"], // 4
  ["charmeleon", "リザード"], // 5
  ["charizard", "リザードン"], // 6
  ["squirtle", "ゼニガメ"], // 7
  ["wartortle", "カメール"], // 8
  ["blastoise", "カメックス"], // 9
  ["caterpie", "キャタピー"], // 10
  ["metapod", "トランセル"], // 11
  ["butterfree", "バタフリー"], // 12
  ["weedle", "ビードル"], // 13
  ["kakuna", "コクーン"], // 14
  ["beedrill", "スピアー"], // 15
  ["pidgey", "ポッポ"], // 16
  ["pidgeotto", "ピジョン"], // 17
  ["pidgeot", "ピジョット"], // 18
  ["rattata", "コラッタ"], // 19
  ["raticate", "ラッタ"], // 20
  ["spearow", "オニスズメ"], // 21
  ["fearow", "オニドリル"], // 22
  ["ekans", "アーボ"], // 23
  ["arbok", "アーボック"], // 24
  ["pikachu", "ピカチュウ"], // 25
  ["raichu", "ライチュウ"], // 26
  ["sandshrew", "サンド"], // 27
  ["sandslash", "サンドパン"], // 28
  ["nidoran-f", "ニドラン♀"], // 29
  ["nidorina", "ニドリーナ"], // 30
  ["nidoqueen", "ニドクイン"], // 31
  ["nidoran-m", "ニドラン♂"], // 32
  ["nidorino", "ニドリーノ"], // 33
  ["nidoking", "ニドキング"], // 34
  ["clefairy", "ピッピ"], // 35
  ["clefable", "ピクシー"], // 36
  ["vulpix", "ロコン"], // 37
  ["ninetales", "キュウコン"], // 38
  ["jigglypuff", "プリン"], // 39
  ["wigglytuff", "プクリン"], // 40
  ["zubat", "ズバット"], // 41
  ["golbat", "ゴルバット"], // 42
  ["oddish", "ナゾノクサ"], // 43
  ["gloom", "クサイハナ"], // 44
  ["vileplume", "ラフレシア"], // 45
  ["paras", "パラス"], // 46
  ["parasect", "パラセクト"], // 47
  ["venonat", "コンパン"], // 48
  ["venomoth", "モルフォン"], // 49
  ["diglett", "ディグダ"], // 50
  ["diglett", "ディグダ"], // 50
  ["dugtrio", "ダグトリオ"], // 51
  ["meowth", "ニャース"], // 52
  ["persian", "ペルシアン"], // 53
  ["psyduck", "コダック"], // 54
  ["golduck", "ゴルダック"], // 55
  ["mankey", "マンキー"], // 56
  ["primeape", "オコリザル"], // 57
  ["growlithe", "ガーディ"], // 58
  ["arcanine", "ウインディ"], // 59
  ["poliwag", "ニョロモ"], // 60
  ["poliwhirl", "ニョロゾ"], // 61
  ["poliwrath", "ニョロボン"], // 62
  ["abra", "ケーシィ"], // 63
  ["kadabra", "ユンゲラー"], // 64
  ["alakazam", "フーディン"], // 65
  ["machop", "ワンリキー"], // 66
  ["machoke", "ゴーリキー"], // 67
  ["machamp", "カイリキー"], // 68
  ["bellsprout", "マダツボミ"], // 69
  ["weepinbell", "ウツドン"], // 70
  ["victreebel", "ウツボット"], // 71
  ["tentacool", "メノクラゲ"], // 72
  ["tentacruel", "ドククラゲ"], // 73
  ["geodude", "イシツブテ"], // 74
  ["graveler", "ゴローン"], // 75
  ["golem", "ゴローニャ"], // 76
  ["ponyta", "ポニータ"], // 77
  ["rapidash", "ギャロップ"], // 78
  ["slowpoke", "ヤドン"], // 79
  ["slowbro", "ヤドラン"], // 80
  ["magnemite", "コイル"], // 81
  ["magneton", "レアコイル"], // 82
  ["farfetchd", "カモネギ"], // 83
  ["doduo", "ドードー"], // 84
  ["dodrio", "ドードリオ"], // 85
  ["seel", "パウワウ"], // 86
  ["dewgong", "ジュゴン"], // 87
  ["grimer", "ベトベター"], // 88
  ["muk", "ベトベトン"], // 89
  ["shellder", "シェルダー"], // 90
  ["cloyster", "パルシェン"], // 91
  ["gastly", "ゴース"], // 92
  ["haunter", "ゴースト"], // 93
  ["gengar", "ゲンガー"], // 94
  ["onix", "イワーク"], // 95
  ["drowzee", "スリープ"], // 96
  ["hypno", "スリーパー"], // 97
  ["krabby", "クラブ"], // 98
  ["kingler", "キングラー"], // 99
  ["voltorb", "ビリリダマ"], // 100
  ["voltorb", "ビリリダマ"], //  100
  ["electrode", "マルマイン"], //  101
  ["exeggcute", "タマタマ"], //  102
  ["exeggutor", "ナッシー"], //  103
  ["cubone", "カラカラ"], //  104
  ["marowak", "ガラガラ"], //  105
  ["hitmonlee", "サワムラー"], //  106
  ["hitmonchan", "エビワラー"], //  107
  ["lickitung", "ベロリンガ"], //  108
  ["koffing", "ドガース"], //  109
  ["weezing", "マタドガス"], //  110
  ["rhyhorn", "サイホーン"], //  111
  ["rhydon", "サイドン"], //  112
  ["chansey", "ラッキー"], //  113
  ["tangela", "モンジャラ"], //  114
  ["kangaskhan", "ガルーラ"], //  115
  ["horsea", "タッツー"], //  116
  ["seadra", "シードラ"], //  117
  ["goldeen", "トサキント"], //  118
  ["seaking", "アズマオウ"], //  119
  ["staryu", "ヒトデマン"], //  120
  ["starmie", "スターミー"], //  121
  ["mr-mime", "バリヤード"], //  122
  ["scyther", "ストライク"], //  123
  ["jynx", "ルージュラ"], //  124
  ["electabuzz", "エレブー"], //  125
  ["magmar", "ブーバー"], //  126
  ["pinsir", "カイロス"], //  127
  ["tauros", "ケンタロス"], //  128
  ["magikarp", "コイキング"], //  129
  ["gyarados", "ギャラドス"], //  130
  ["lapras", "ラプラス"], //  131
  ["ditto", "メタモン"], //  132
  ["eevee", "イーブイ"], //  133
  ["vaporeon", "シャワーズ"], //  134
  ["jolteon", "サンダース"], //  135
  ["flareon", "ブースター"], //  136
  ["porygon", "ポリゴン"], //  137
  ["omanyte", "オムナイト"], //  138
  ["omastar", "オムスター"], //  139
  ["kabuto", "カブト"], //  140
  ["kabutops", "カブトプス"], //  141
  ["aerodactyl", "プテラ"], //  142
  ["snorlax", "カビゴン"], //  143
  ["articuno", "フリーザー"], //  144
  ["zapdos", "サンダー"], //  145
  ["moltres", "ファイヤー"], //  146
  ["dratini", "ミニリュウ"], //  147
  ["dragonair", "ハクリュー"], //  148
  ["dragonite", "カイリュー"], //  149
  ["mewtwo", "ミュウツー"], //  150
  ["mew", "ミュウ"], //  151
  ["chikorita", "チコリータ"], //  152
  ["bayleef", "ベイリーフ"], //  153
  ["meganium", "メガニウム"], //  154
  ["cyndaquil", "ヒノアラシ"], //  155
  ["quilava", "マグマラシ"], //  156
  ["typhlosion", "バクフーン"], //  157
  ["totodile", "ワニノコ"], //  158
  ["croconaw", "アリゲイツ"], //  159
  ["feraligatr", "オーダイル"], //  160
  ["sentret", "オタチ"], //  161
  ["furret", "オオタチ"], //  162
  ["hoothoot", "ホーホー"], //  163
  ["noctowl", "ヨルノズク"], //  164
  ["ledyba", "レディバ"], //  165
  ["ledian", "レディアン"], //  166
  ["spinarak", "イトマル"], //  167
  ["ariados", "アリアドス"], //  168
  ["crobat", "クロバット"], //  169
  ["chinchou", "チョンチー"], //  170
  ["lanturn", "ランターン"], //  171
  ["pichu", "ピチュー"], //  172
  ["cleffa", "ピィ"], //  173
  ["igglybuff", "ププリン"], //  174
  ["togepi", "トゲピー"], //  175
  ["togetic", "トゲチック"], //  176
  ["natu", "ネイティ"], //  177
  ["xatu", "ネイティオ"], //  178
  ["mareep", "メリープ"], //  179
  ["flaaffy", "モココ"], //  180
  ["ampharos", "デンリュウ"], //  181
  ["bellossom", "キレイハナ"], //  182
  ["marill", "マリル"], //  183
  ["azumarill", "マリルリ"], //  184
  ["sudowoodo", "ウソッキー"], //  185
  ["politoed", "ニョロトノ"], //  186
  ["hoppip", "ハネッコ"], //  187
  ["skiploom", "ポポッコ"], //  188
  ["jumpluff", "ワタッコ"], //  189
  ["aipom", "エイパム"], //  190
  ["sunkern", "ヒマナッツ"], //  191
  ["sunflora", "キマワリ"], //  192
  ["yanma", "ヤンヤンマ"], //  193
  ["wooper", "ウパー"], //  194
  ["quagsire", "ヌオー"], //  195
  ["espeon", "エーフィ"], //  196
  ["umbreon", "ブラッキー"], //  197
  ["murkrow", "ヤミカラス"], //  198
  ["slowking", "ヤドキング"], //  199
  ["misdreavus", "ムウマ"], //  200
  ["unown", "アンノーン"], //  201
  ["wobbuffet", "ソーナンス"], //  202
  ["girafarig", "キリンリキ"], //  203
  ["pineco", "クヌギダマ"], //  204
  ["forretress", "フォレトス"], //  205
  ["dunsparce", "ノコッチ"], //  206
  ["gligar", "グライガー"], //  207
  ["steelix", "ハガネール"], //  208
  ["snubbull", "ブルー"], //  209
  ["granbull", "グランブル"], //  210
  ["qwilfish", "ハリーセン"], //  211
  ["scizor", "ハッサム"], //  212
  ["shuckle", "ツボツボ"], //  213
  ["heracross", "ヘラクロス"], //  214
  ["sneasel", "ニューラ"], //  215
  ["teddiursa", "ヒメグマ"], //  216
  ["ursaring", "リングマ"], //  217
  ["slugma", "マグマッグ"], //  218
  ["magcargo", "マグカルゴ"], //  219
  ["swinub", "ウリムー"], //  220
  ["piloswine", "イノムー"], //  221
  ["corsola", "サニーゴ"], //  222
  ["remoraid", "テッポウオ"], //  223
  ["octillery", "オクタン"], //  224
  ["delibird", "デリバード"], //  225
  ["mantine", "マンタイン"], //  226
  ["skarmory", "エアームド"], //  227
  ["houndour", "デルビル"], //  228
  ["houndoom", "ヘルガー"], //  229
  ["kingdra", "キングドラ"], //  230
  ["phanpy", "ゴマゾウ"], //  231
  ["donphan", "ドンファン"], //  232
  ["porygon2", "ポリゴン2"], //  233
  ["stantler", "オドシシ"], //  234
  ["smeargle", "ドーブル"], //  235
  ["tyrogue", "バルキー"], //  236
  ["hitmontop", "カポエラー"], //  237
  ["smoochum", "ムチュール"], //  238
  ["elekid", "エレキッド"], //  239
  ["magby", "ブビィ"], //  240
  ["miltank", "ミルタンク"], //  241
  ["blissey", "ハピナス"], //  242
  ["raikou", "ライコウ"], //  243
  ["entei", "エンテイ"], //  244
  ["suicune", "スイクン"], //  245
  ["larvitar", "ヨーギラス"], //  246
  ["pupitar", "サナギラス"], //  247
  ["tyranitar", "バンギラス"], //  248
  ["lugia", "ルギア"], //  249
  ["hoOh", "ホウオウ"], //  250
  ["celebi", "セレビィ"], //  251
  ["treecko", "キモリ"], //  252
  ["grovyle", "ジュプトル"], //  253
  ["sceptile", "ジュカイン"], //  254
  ["torchic", "アチャモ"], //  255
  ["combusken", "ワカシャモ"], //  256
  ["blaziken", "バシャーモ"], //  257
  ["mudkip", "ミズゴロウ"], //  258
  ["marshtomp", "ヌマクロー"], //  259
  ["swampert", "ラグラージ"], //  260
  ["poochyena", "ポチエナ"], //  261
  ["mightyena", "グラエナ"], //  262
  ["zigzagoon", "ジグザグマ"], //  263
  ["linoone", "マッスグマ"], //  264
  ["wurmple", "ケムッソ"], //  265
  ["silcoon", "カラサリス"], //  266
  ["beautifly", "アゲハント"], //  267
  ["cascoon", "マユルド"], //  268
  ["dustox", "ドクケイル"], //  269
  ["lotad", "ハスボー"], //  270
  ["lombre", "ハスブレロ"], //  271
  ["ludicolo", "ルンパッパ"], //  272
  ["seedot", "タネボー"], //  273
  ["nuzleaf", "コノハナ"], //  274
  ["shiftry", "ダーテング"], //  275
  ["taillow", "スバメ"], //  276
  ["swellow", "オオスバメ"], //  277
  ["wingull", "キャモメ"], //  278
  ["pelipper", "ペリッパー"], //  279
  ["ralts", "ラルトス"], //  280
  ["kirlia", "キルリア"], //  281
  ["gardevoir", "サーナイト"], //  282
  ["surskit", "アメタマ"], //  283
  ["masquerain", "アメモース"], //  284
  ["unown", "アンノーン"], //  201
  ["wobbuffet", "ソーナンス"], //  202
  ["girafarig", "キリンリキ"], //  203
  ["pineco", "クヌギダマ"], //  204
  ["forretress", "フォレトス"], //  205
  ["dunsparce", "ノコッチ"], //  206
  ["gligar", "グライガー"], //  207
  ["steelix", "ハガネール"], //  208
  ["snubbull", "ブルー"], //  209
  ["granbull", "グランブル"], //  210
  ["qwilfish", "ハリーセン"], //  211
  ["scizor", "ハッサム"], //  212
  ["shuckle", "ツボツボ"], //  213
  ["heracross", "ヘラクロス"], //  214
  ["sneasel", "ニューラ"], //  215
  ["teddiursa", "ヒメグマ"], //  216
  ["ursaring", "リングマ"], //  217
  ["slugma", "マグマッグ"], //  218
  ["magcargo", "マグカルゴ"], //  219
  ["swinub", "ウリムー"], //  220
  ["piloswine", "イノムー"], //  221
  ["corsola", "サニーゴ"], //  222
  ["remoraid", "テッポウオ"], //  223
  ["octillery", "オクタン"], //  224
  ["delibird", "デリバード"], //  225
  ["mantine", "マンタイン"], //  226
  ["skarmory", "エアームド"], //  227
  ["houndour", "デルビル"], //  228
  ["houndoom", "ヘルガー"], //  229
  ["kingdra", "キングドラ"], //  230
  ["phanpy", "ゴマゾウ"], //  231
  ["donphan", "ドンファン"], //  232
  ["porygon2", "ポリゴン2"], //  233
  ["stantler", "オドシシ"], //  234
  ["smeargle", "ドーブル"], //  235
  ["tyrogue", "バルキー"], //  236
  ["hitmontop", "カポエラー"], //  237
  ["smoochum", "ムチュール"], //  238
  ["elekid", "エレキッド"], //  239
  ["magby", "ブビィ"], //  240
  ["miltank", "ミルタンク"], //  241
  ["blissey", "ハピナス"], //  242
  ["raikou", "ライコウ"], //  243
  ["entei", "エンテイ"], //  244
  ["suicune", "スイクン"], //  245
  ["larvitar", "ヨーギラス"], //  246
  ["pupitar", "サナギラス"], //  247
  ["tyranitar", "バンギラス"], //  248
  ["lugia", "ルギア"], //  249
  ["ho-oh", "ホウオウ"], //  250
  ["celebi", "セレビィ"], //  251
  ["treecko", "キモリ"], //  252
  ["grovyle", "ジュプトル"], //  253
  ["sceptile", "ジュカイン"], //  254
  ["torchic", "アチャモ"], //  255
  ["combusken", "ワカシャモ"], //  256
  ["blaziken", "バシャーモ"], //  257
  ["mudkip", "ミズゴロウ"], //  258
  ["marshtomp", "ヌマクロー"], //  259
  ["swampert", "ラグラージ"], //  260
  ["poochyena", "ポチエナ"], //  261
  ["mightyena", "グラエナ"], //  262
  ["zigzagoon", "ジグザグマ"], //  263
  ["linoone", "マッスグマ"], //  264
  ["wurmple", "ケムッソ"], //  265
  ["silcoon", "カラサリス"], //  266
  ["beautifly", "アゲハント"], //  267
  ["cascoon", "マユルド"], //  268
  ["dustox", "ドクケイル"], //  269
  ["lotad", "ハスボー"], //  270
  ["lombre", "ハスブレロ"], //  271
  ["ludicolo", "ルンパッパ"], //  272
  ["seedot", "タネボー"], //  273
  ["nuzleaf", "コノハナ"], //  274
  ["shiftry", "ダーテング"], //  275
  ["taillow", "スバメ"], //  276
  ["swellow", "オオスバメ"], //  277
  ["wingull", "キャモメ"], //  278
  ["pelipper", "ペリッパー"], //  279
  ["ralts", "ラルトス"], //  280
  ["kirlia", "キルリア"], //  281
  ["gardevoir", "サーナイト"], //  282
  ["surskit", "アメタマ"], //  283
  ["masquerain", "アメモース"], //  284
  ["shroomish", "キノココ"], //  285
  ["breloom", "キノガッサ"], //  286
  ["slakoth", "ナマケロ"], //  287
  ["vigoroth", "ヤルキモノ"], //  288
  ["slaking", "ケッキング"], //  289
  ["nincada", "ツチニン"], //  290
  ["ninjask", "テッカニン"], //  291
  ["shedinja", "ヌケニン"], //  292
  ["whismur", "ゴニョニョ"], //  293
  ["loudred", "ドゴーム"], //  294
  ["exploud", "バクオング"], //  295
  ["makuhita", "マクノシタ"], //  296
  ["hariyama", "ハリテヤマ"], //  297
  ["azurill", "ルリリ"], //  298
  ["nosepass", "ノズパス"], //  299
  ["skitty", "エネコ"], //  300
  ["delcatty", "エネコロロ"], //  301
  ["sableye", "ヤミラミ"], //  302
  ["mawile", "クチート"], //  303
  ["aron", "ココドラ"], //  304
  ["lairon", "コドラ"], //  305
  ["aggron", "ボスゴドラ"], //  306
  ["meditite", "アサナン"], //  307
  ["medicham", "チャーレム"], //  308
  ["electrike", "ラクライ"], //  309
  ["manectric", "ライボルト"], //  310
  ["plusle", "プラスル"], //  311
  ["minun", "マイナン"], //  312
  ["volbeat", "バルビート"], //  313
  ["illumise", "イルミーゼ"], //  314
  ["roselia", "ロゼリア"], //  315
  ["gulpin", "ゴクリン"], //  316
  ["swalot", "マルノーム"], //  317
  ["carvanha", "キバニア"], //  318
  ["sharpedo", "サメハダー"], //  319
  ["wailmer", "ホエルコ"], //  320
  ["wailord", "ホエルオー"], //  321
  ["numel", "ドンメル"], //  322
  ["camerupt", "バクーダ"], //  323
  ["torkoal", "コータス"], //  324
  ["spoink", "バネブー"], //  325
  ["grumpig", "ブーピッグ"], //  326
  ["spinda", "パッチール"], //  327
  ["trapinch", "ナックラー"], //  328
  ["vibrava", "ビブラーバ"], //  329
  ["flygon", "フライゴン"], //  330
  ["cacnea", "サボネア"], //  331
  ["cacturne", "ノクタス"], //  332
  ["swablu", "チルット"], //  333
  ["altaria", "チルタリス"], //  334
  ["zangoose", "ザングース"], //  335
  ["seviper", "ハブネーク"], //  336
  ["lunatone", "ルナトーン"], //  337
  ["solrock", "ソルロック"], //  338
  ["barboach", "ドジョッチ"], //  339
  ["whiscash", "ナマズン"], //  340
  ["corphish", "ヘイガニ"], //  341
  ["crawdaunt", "シザリガー"], //  342
  ["baltoy", "ヤジロン"], //  343
  ["claydol", "ネンドール"], //  344
  ["lileep", "リリーラ"], //  345
  ["cradily", "ユレイドル"], //  346
  ["anorith", "アノプス"], //  347
  ["armaldo", "アーマルド"], //  348
  ["feebas", "ヒンバス"], //  349
  ["milotic", "ミロカロス"], //  350
  ["castform", "ポワルン"], //  351
  ["kecleon", "カクレオン"], //  352
  ["shuppet", "カゲボウズ"], //  353
  ["banette", "ジュペッタ"], //  354
  ["duskull", "ヨマワル"], //  355
  ["dusclops", "サマヨール"], //  356
  ["tropius", "トロピウス"], //  357
  ["chimecho", "チリーン"], //  358
  ["absol", "アブソル"], //  359
  ["wynaut", "ソーナノ"], //  360
  ["snorunt", "ユキワラシ"], //  361
  ["glalie", "オニゴーリ"], //  362
  ["spheal", "タマザラシ"], //  363
  ["sealeo", "トドグラー"], //  364
  ["walrein", "トドゼルガ"], //  365
  ["clamperl", "パールル"], //  366
  ["huntail", "ハンテール"], //  367
  ["gorebyss", "サクラビス"], //  368
  ["relicanth", "ジーランス"], //  369
  ["luvdisc", "ラブカス"], //  370
  ["bagon", "タツベイ"], //  371
  ["shelgon", "コモルー"], //  372
  ["salamence", "ボーマンダ"], //  373
  ["beldum", "ダンバル"], //  374
  ["metang", "メタング"], //  375
  ["metagross", "メタグロス"], //  376
  ["regirock", "レジロック"], //  377
  ["regice", "レジアイス"], //  378
  ["registeel", "レジスチル"], //  379
  ["latias", "ラティアス"], //  380
  ["latios", "ラティオス"], //  381
  ["kyogre", "カイオーガ"], //  382
  ["groudon", "グラードン"], //  383
  ["rayquaza", "レックウザ"], //  384
  ["jirachi", "ジラーチ"], //  385
  ["deoxys-normal", "デオキシス"], //  386
  ["turtwig", "ナエトル"], //  387
  ["grotle", "ハヤシガメ"], //  388
  ["torterra", "ドダイトス"], //  389
  ["chimchar", "ヒコザル"], //  390
  ["monferno", "モウカザル"], //  391
  ["infernape", "ゴウカザル"], //  392
  ["piplup", "ポッチャマ"], //  393
  ["prinplup", "ポッタイシ"], //  394
  ["empoleon", "エンペルト"], //  395
  ["starly", "ムックル"], //  396
  ["staravia", "ムクバード"], //  397
  ["staraptor", "ムクホーク"], //  398
  ["bidoof", "ビッパ"], //  399
  ["bibarel", "ビーダル"], //  400
  ["kricketot", "コロボーシ"], //  401
  ["kricketune", "コロトック"], //  402
  ["shinx", "コリンク"], //  403
  ["luxio", "ルクシオ"], //  404
  ["luxray", "レントラー"], //  405
  ["budew", "スボミー"], //  406
  ["roserade", "ロズレイド"], //  407
  ["cranidos", "ズガイドス"], //  408
  ["rampardos", "ラムパルド"], //  409
  ["shieldon", "タテトプス"], //  410
  ["bastiodon", "トリデプス"], //  411
  ["burmy", "ミノムッチ"], //  412
  ["wormadam", "ミノマダム"], //  413
  ["mothim", "ガーメイル"], //  414
  ["combee", "ミツハニー"], //  415
  ["vespiquen", "ビークイン"], //  416
  ["pachirisu", "パチリス"], //  417
  ["buizel", "ブイゼル"], //  418
  ["floatzel", "フローゼル"], //  419
  ["cherubi", "チェリンボ"], //  420
  ["cherrim", "チェリム"], //  421
  ["shellos", "カラナクシ"], //  422
  ["gastrodon", "トリトドン"], //  423
  ["ambipom", "エテボース"], //  424
  ["drifloon", "フワンテ"], //  425
  ["drifblim", "フワライド"], //  426
  ["buneary", "ミミロル"], //  427
  ["lopunny", "ミミロップ"], //  428
  ["mismagius", "ムウマージ"], //  429
  ["honchkrow", "ドンカラス"], //  430
  ["glameow", "ニャルマー"], //  431
  ["purugly", "ブニャット"], //  432
  ["chingling", "リーシャン"], //  433
  ["stunky", "スカンプー"], //  434
  ["skuntank", "スカタンク"], //  435
  ["bronzor", "ドーミラー"], //  436
  ["bronzong", "ドータクン"], //  437
  ["bonsly", "ウソハチ"], //  438
  ["mimejr", "マネネ"], //  439
  ["happiny", "ピンプク"], //  440
  ["chatot", "ペラップ"], //  441
  ["spiritomb", "ミカルゲ"], //  442
  ["gible", "フカマル"], //  443
  ["gabite", "ガバイト"], //  444
  ["garchomp", "ガブリアス"], //  445
  ["munchlax", "ゴンベ"], //  446
  ["riolu", "リオル"], //  447
  ["lucario", "ルカリオ"], //  448
  ["hippopotas", "ヒポポタス"], //  449
  ["hippowdon", "カバルドン"], //  450
  ["skorupi", "スコルピ"], //  451
  ["drapion", "ドラピオン"], //  452
  ["croagunk", "グレッグル"], //  453
  ["toxicroak", "ドクロッグ"], //  454
  ["carnivine", "マスキッパ"], //  455
  ["finneon", "ケイコウオ"], //  456
  ["lumineon", "ネオラント"], //  457
  ["mantyke", "タマンタ"], //  458
  ["snover", "ユキカブリ"], //  459
  ["abomasnow", "ユキノオー"], //  460
  ["weavile", "マニューラ"], //  461
  ["magnezone", "ジバコイル"], //  462
  ["lickilicky", "ベロベルト"], //  463
  ["rhyperior", "ドサイドン"], //  464
  ["tangrowth", "モジャンボ"], //  465
  ["electivire", "エレキブル"], //  466
  ["magmortar", "ブーバーン"], //  467
  ["togekiss", "トゲキッス"], //  468
  ["yanmega", "メガヤンマ"], //  469
  ["leafeon", "リーフィア"], //  470
  ["glaceon", "グレイシア"], //  471
  ["gliscor", "グライオン"], //  472
  ["mamoswine", "マンムー"], //  473
  ["porygon-z", "ポリゴンZ"], //  474
  ["gallade", "エルレイド"], //  475
  ["probopass", "ダイノーズ"], //  476
  ["dusknoir", "ヨノワール"], //  477
  ["froslass", "ユキメノコ"], //  478
  ["rotom", "ロトム"], //  479
  ["uxie", "ユクシー"], //  480
  ["mesprit", "エムリット"], //  481
  ["azelf", "アグノム"], //  482
  ["dialga", "ディアルガ"], //  483
  ["palkia", "パルキア"], //  484
  ["heatran", "ヒードラン"], //  485
  ["regigigas", "レジギガス"], //  486
  ["giratina-altered", "ギラティナ"], //  487
  ["cresselia", "クレセリア"], //  488
  ["phione", "フィオネ"], //  489
  ["manaphy", "マナフィ"], //  490
  ["darkrai", "ダークライ"], //  491
  ["shaymin-land", "シェイミ"], //  492
  ["arceus", "アルセウス"], //  493
  ["victini", "ビクティニ"], //  494
  ["snivy", "ツタージャ"], //  495
  ["servine", "ジャノビー"], //  496
  ["serperior", "ジャローダ"], //  497
  ["tepig", "ポカブ"], //  498
  ["pignite", "チャオブー"], //  499
  ["emboar", "エンブオー"], //  500
  ["oshawott", "ミジュマル"], //  501
  ["dewott", "フタチマル"], //  502
  ["samurott", "ダイケンキ"], //  503
  ["patrat", "ミネズミ"], //  504
  ["watchog", "ミルホッグ"], //  505
  ["lillipup", "ヨーテリー"], //  506
  ["herdier", "ハーデリア"], //  507
  ["stoutland", "ムーランド"], //  508
  ["purrloin", "チョロネコ"], //  509
  ["liepard", "レパルダス"], //  510
  ["pansage", "ヤナップ"], //  511
  ["simisage", "ヤナッキー"], //  512
  ["pansear", "バオップ"], //  513
  ["simisear", "バオッキー"], //  514
  ["panpour", "ヒヤップ"], //  515
  ["simipour", "ヒヤッキー"], //  516
  ["munna", "ムンナ"], //  517
  ["musharna", "ムシャーナ"], //  518
  ["pidove", "マメパト"], //  519
  ["tranquill", "ハトーボー"], //  520
  ["unfezant", "ケンホロウ"], //  521
  ["blitzle", "シママ"], //  522
  ["zebstrika", "ゼブライカ"], //  523
  ["roggenrola", "ダンゴロ"], //  524
  ["boldore", "ガントル"], //  525
  ["gigalith", "ギガイアス"], //  526
  ["woobat", "コロモリ"], //  527
  ["swoobat", "ココロモリ"], //  528
  ["drilbur", "モグリュー"], //  529
  ["excadrill", "ドリュウズ"], //  530
  ["audino", "タブンネ"], //  531
  ["timburr", "ドッコラー"], //  532
  ["gurdurr", "ドテッコツ"], //  533
  ["conkeldurr", "ローブシン"], //  534
  ["tympole", "オタマロ"], //  535
  ["palpitoad", "ガマガル"], //  536
  ["seismitoad", "ガマゲロゲ"], //  537
  ["throh", "ナゲキ"], //  538
  ["sawk", "ダゲキ"], //  539
  ["sewaddle", "クルミル"], //  540
  ["swadloon", "クルマユ"], //  541
  ["leavanny", "ハハコモリ"], //  542
  ["venipede", "フシデ"], //  543
  ["whirlipede", "ホイーガ"], //  544
  ["scolipede", "ペンドラー"], //  545
  ["cottonee", "モンメン"], //  546
  ["whimsicott", "エルフーン"], //  547
  ["petilil", "チュリネ"], //  548
  ["lilligant", "ドレディア"], //  549
  ["basculin-red-striped", "バスラオ"], //  550
  ["sandile", "メグロコ"], //  551
  ["krokorok", "ワルビル"], //  552
  ["krookodile", "ワルビアル"], //  553
  ["darumaka", "ダルマッカ"], //  554
  ["darmanitan-standard", "ヒヒダルマ"], //  555
  ["maractus", "マラカッチ"], //  556
  ["dwebble", "イシズマイ"], //  557
  ["crustle", "イワパレス"], //  558
  ["scraggy", "ズルッグ"], //  559
  ["scrafty", "ズルズキン"], //  560
  ["sigilyph", "シンボラー"], //  561
  ["yamask", "デスマス"], //  562
  ["cofagrigus", "デスカーン"], //  563
  ["tirtouga", "プロトーガ"], //  564
  ["carracosta", "アバゴーラ"], //  565
  ["archen", "アーケン"], //  566
  ["archeops", "アーケオス"], //  567
  ["trubbish", "ヤブクロン"], //  568
  ["garbodor", "ダストダス"], //  569
  ["zorua", "ゾロア"], //  570
  ["zoroark", "ゾロアーク"], //  571
  ["minccino", "チラーミィ"], //  572
  ["cinccino", "チラチーノ"], //  573
  ["gothita", "ゴチム"], //  574
  ["gothorita", "ゴチミル"], //  575
  ["gothitelle", "ゴチルゼル"], //  576
  ["solosis", "ユニラン"], //  577
  ["duosion", "ダブラン"], //  578
  ["reuniclus", "ランクルス"], //  579
  ["ducklett", "コアルヒー"], //  580
  ["swanna", "スワンナ"], //  581
  ["vanillite", "バニプッチ"], //  582
  ["vanillish", "バニリッチ"], //  583
  ["vanilluxe", "バイバニラ"], //  584
  ["deerling", "シキジカ"], //  585
  ["sawsbuck", "メブキジカ"], //  586
  ["emolga", "エモンガ"], //  587
  ["karrablast", "カブルモ"], //  588
  ["escavalier", "シュバルゴ"], //  589
  ["foongus", "タマゲタケ"], //  590
  ["amoonguss", "モロバレル"], //  591
  ["frillish", "プルリル"], //  592
  ["jellicent", "ブルンゲル"], //  593
  ["alomomola", "ママンボウ"], //  594
  ["joltik", "バチュル"], //  595
  ["galvantula", "デンチュラ"], //  596
  ["ferroseed", "テッシード"], //  597
  ["ferrothorn", "ナットレイ"], //  598
  ["klink", "ギアル"], //  599
  ["klang", "ギギアル"], //  600
  ["klinklang", "ギギギアル"], //  601
  ["tynamo", "シビシラス"], //  602
  ["eelektrik", "シビビール"], //  603
  ["eelektross", "シビルドン"], //  604
  ["elgyem", "リグレー"], //  605
  ["beheeyem", "オーベム"], //  606
  ["litwick", "ヒトモシ"], //  607
  ["lampent", "ランプラー"], //  608
  ["chandelure", "シャンデラ"], //  609
  ["axew", "キバゴ"], //  610
  ["fraxure", "オノンド"], //  611
  ["haxorus", "オノノクス"], //  612
  ["cubchoo", "クマシュン"], //  613
  ["beartic", "ツンベアー"], //  614
  ["cryogonal", "フリージオ"], //  615
  ["shelmet", "チョボマキ"], //  616
  ["accelgor", "アギルダー"], //  617
  ["stunfisk", "マッギョ"], //  618
  ["mienfoo", "コジョフー"], //  619
  ["mienshao", "コジョンド"], //  620
  ["druddigon", "クリムガン"], //  621
  ["golett", "ゴビット"], //  622
  ["golurk", "ゴルーグ"], //  623
  ["pawniard", "コマタナ"], //  624
  ["bisharp", "キリキザン"], //  625
  ["bouffalant", "バッフロン"], //  626
  ["rufflet", "ワシボン"], //  627
  ["braviary", "ウォーグル"], //  628
  ["vullaby", "バルチャイ"], //  629
  ["mandibuzz", "バルジーナ"], //  630
  ["heatmor", "クイタラン"], //  631
  ["durant", "アイアント"], //  632
  ["deino", "モノズ"], //  633
  ["zweilous", "ジヘッド"], //  634
  ["hydreigon", "サザンドラ"], //  635
  ["larvesta", "メラルバ"], //  636
  ["volcarona", "ウルガモス"], //  637
  ["cobalion", "コバルオン"], //  638
  ["terrakion", "テラキオン"], //  639
  ["virizion", "ビリジオン"], //  640
  ["tornadus-incarnate", "トルネロス"], //  641
  ["thundurus-incarnate", "ボルトロス"], //  642
  ["reshiram", "レシラム"], //  643
  ["zekrom", "ゼクロム"], //  644
  ["landorus-incarnate", "ランドロス"], //  645
  ["kyurem", "キュレム"], //  646
  ["keldeo-ordinary", "ケルディオ"], //  647
  ["meloetta-aria", "メロエッタ"], //  648
  ["genesect", "ゲノセクト"], //  649
]);
