export const typeData = new Map<string, { label: string; color: number }>([
  ["normal", { label: "ノーマル", color: 0x949897 }],
  ["fighting", { label: "かくとう", color: 0xfa4439 }],
  ["flying", { label: "ひこう", color: 0x97b0e7 }],
  ["poison", { label: "どく", color: 0xa040a0 }],
  ["ground", { label: "じめん", color: 0xe0c068 }],
  ["rock", { label: "いわ", color: 0xb8a038 }],
  ["bug", { label: "むし", color: 0xa8b820 }],
  ["ghost", { label: "ゴースト", color: 0x705898 }],
  ["steel", { label: "はがね", color: 0x4d989e }],
  ["fire", { label: "ほのお", color: 0xf08030 }],
  ["water", { label: "みず", color: 0x47bafc }],
  ["grass", { label: "くさ", color: 0x78c850 }],
  ["electric", { label: "でんき", color: 0xf8d030 }],
  ["psychic", { label: "エスパー", color: 0xf85888 }],
  ["ice", { label: "こおり", color: 0x9ef0f0 }],
  ["dragon", { label: "ドラゴン", color: 0x066fb5 }],
  ["dark", { label: "あく", color: 0x705848 }],
  ["fairy", { label: "フェアリー", color: 0xee99ac }],
  ["stellar", { label: "ステラ", color: 0x7cc7b2 }],
]);
